services:
  flask-quiz-app-saa:
    build: .
    ports:
      - "5001:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0
    volumes:
      - ./exam_results.txt:/app/exam_results.txt
      - ./solution_architect/:/app/solution_architect/
